// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetArtifact(arg1) {
  return window['go']['main']['App']['GetArtifact'](arg1);
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function ListArtifacts(arg1) {
  return window['go']['main']['App']['ListArtifacts'](arg1);
}

export function MarkDone(arg1) {
  return window['go']['main']['App']['MarkDone'](arg1);
}

export function OpenNative(arg1) {
  return window['go']['main']['App']['OpenNative'](arg1);
}

export function Search(arg1, arg2) {
  return window['go']['main']['App']['Search'](arg1, arg2);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}
