// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetArtifact(arg1:string):Promise<main.ArtifactDetail>;

export function GetStatus():Promise<main.Status>;

export function ListArtifacts(arg1:Array<string>):Promise<Array<main.Artifact>>;

export function MarkDone(arg1:string):Promise<void>;

export function OpenNative(arg1:main.Artifact):Promise<void>;

export function Search(arg1:string,arg2:number):Promise<Array<main.Artifact>>;

export function ShowWindow():Promise<void>;
