// Package styles provides the lipgloss theme and icon definitions for the Clara TUI.
// Call SetTheme to switch color palettes at runtime; pass nil for native 16-color mode.
package styles

import (
	"github.com/charmbracelet/lipgloss"
	bubbletint "github.com/lrstanley/bubbletint/v2"
)

// Active color palette — updated by SetTheme.
var (
	ColorBg            lipgloss.Color
	ColorFg            lipgloss.Color
	ColorMuted         lipgloss.Color
	ColorBorderActive  lipgloss.Color // focused pane border
	ColorBorderInactive lipgloss.Color // unfocused pane border

	// Heat gradient: low → urgent.
	ColorHeatLow    lipgloss.Color
	ColorHeatMed    lipgloss.Color
	ColorHeatHigh   lipgloss.Color
	ColorHeatUrgent lipgloss.Color

	// Artifact kind colors.
	ColorReminder   lipgloss.Color
	ColorNote       lipgloss.Color
	ColorFile       lipgloss.Color
	ColorEmail      lipgloss.Color
	ColorBookmark   lipgloss.Color
	ColorLog        lipgloss.Color
	ColorSuggestion lipgloss.Color

	// Status bar.
	ColorHelpBg lipgloss.Color
	ColorHelpFg lipgloss.Color

	// Selected item.
	ColorItemActiveBg lipgloss.Color
)

// Style vars — regenerated by SetTheme.
var (
	FocusedBorder    lipgloss.Style
	UnfocusedBorder  lipgloss.Style
	PaneTitle        lipgloss.Style
	PaneTitleFocused lipgloss.Style
	ItemSelected     lipgloss.Style
	ItemNormal       lipgloss.Style
	Muted            lipgloss.Style
	Bold             lipgloss.Style
	SearchPrompt     lipgloss.Style
)

func init() {
	applyNative()
	regenerateStyles()
}

// SetTheme updates all styles to use the given bubbletint Tint.
// Pass nil to restore native 16-color terminal mode.
func SetTheme(t *bubbletint.Tint) {
	if t == nil {
		applyNative()
	} else {
		applyTint(t)
	}
	regenerateStyles()
}

// applyNative sets all colors to ANSI 16-color terminal values.
// These render correctly in any terminal regardless of color scheme.
func applyNative() {
	ColorBg             = lipgloss.Color("0")
	ColorFg             = lipgloss.Color("15")
	ColorMuted          = lipgloss.Color("8")   // bright black / dark gray
	ColorBorderActive   = lipgloss.Color("2")   // green
	ColorBorderInactive = lipgloss.Color("7")   // white
	ColorHelpBg         = lipgloss.Color("0")   // black
	ColorHelpFg         = lipgloss.Color("15")  // fg
	ColorItemActiveBg   = lipgloss.Color("6")   // cyan

	// Heat: green → yellow → orange (256) → red
	ColorHeatLow    = lipgloss.Color("2")
	ColorHeatMed    = lipgloss.Color("3")
	ColorHeatHigh   = lipgloss.Color("214")
	ColorHeatUrgent = lipgloss.Color("1")

	// Kinds
	ColorReminder   = lipgloss.Color("1")   // red
	ColorNote       = lipgloss.Color("2")   // green
	ColorFile       = lipgloss.Color("4")   // blue
	ColorEmail      = lipgloss.Color("5")   // magenta
	ColorBookmark   = lipgloss.Color("3")   // yellow
	ColorLog        = lipgloss.Color("214") // orange
	ColorSuggestion = lipgloss.Color("6")   // cyan
}

// fromTint converts a *bubbletint.Color to lipgloss.Color, falling back to
// the provided ANSI index string if the tint color is nil.
func fromTint(c *bubbletint.Color, ansiIndex string) lipgloss.Color {
	if c == nil {
		return lipgloss.Color(ansiIndex)
	}
	return lipgloss.Color(c.Hex())
}

// applyTint maps a bubbletint palette onto our color vars.
func applyTint(t *bubbletint.Tint) {
	ColorBg             = fromTint(t.Bg, "0")
	ColorFg             = fromTint(t.Fg, "15")
	ColorMuted          = fromTint(t.BrightBlack, "8")
	ColorBorderActive   = fromTint(t.Green, "2")
	ColorBorderInactive = fromTint(t.White, "7")
	ColorHelpBg         = fromTint(t.Black, "0")
	ColorHelpFg         = fromTint(t.Fg, "15")
	ColorItemActiveBg   = fromTint(t.Cyan, "6")

	ColorHeatLow    = fromTint(t.Green, "2")
	ColorHeatMed    = fromTint(t.Yellow, "3")
	ColorHeatHigh   = fromTint(t.BrightYellow, "214")
	ColorHeatUrgent = fromTint(t.Red, "1")

	ColorReminder   = fromTint(t.Red, "1")
	ColorNote       = fromTint(t.Green, "2")
	ColorFile       = fromTint(t.Blue, "4")
	ColorEmail      = fromTint(t.Purple, "5")
	ColorBookmark   = fromTint(t.Yellow, "3")
	ColorLog        = fromTint(t.BrightYellow, "214")
	ColorSuggestion = fromTint(t.Cyan, "6")
}

// regenerateStyles rebuilds all lipgloss Style objects from the current color vars.
// Called after any theme change.
func regenerateStyles() {
	FocusedBorder = lipgloss.NewStyle().
		BorderStyle(lipgloss.RoundedBorder()).
		BorderForeground(ColorBorderActive).
		Padding(0, 1)

	UnfocusedBorder = lipgloss.NewStyle().
		BorderStyle(lipgloss.RoundedBorder()).
		BorderForeground(ColorBorderInactive).
		Padding(0, 1)

	PaneTitle = lipgloss.NewStyle().
		Bold(true).
		Foreground(ColorMuted).
		Padding(0, 1)

	PaneTitleFocused = lipgloss.NewStyle().
		Bold(true).
		Foreground(ColorBorderActive).
		Padding(0, 1)

	ItemSelected = lipgloss.NewStyle().
		Background(ColorItemActiveBg).
		Foreground(ColorFg).
		Bold(true)

	ItemNormal = lipgloss.NewStyle().
		Foreground(ColorFg)

	Muted = lipgloss.NewStyle().Foreground(ColorMuted)

	Bold = lipgloss.NewStyle().Bold(true)

	SearchPrompt = lipgloss.NewStyle().
		Foreground(ColorBorderActive).
		Bold(true)
}

// HeatColor returns the color for a heat score in [0,1].
func HeatColor(score float64) lipgloss.Color {
	switch {
	case score >= 0.8:
		return ColorHeatUrgent
	case score >= 0.6:
		return ColorHeatHigh
	case score >= 0.35:
		return ColorHeatMed
	default:
		return ColorHeatLow
	}
}

// HeatBar returns a 3-char heat indicator rendered in the appropriate color.
func HeatBar(score float64) string {
	color := HeatColor(score)
	var bar string
	switch {
	case score >= 0.8:
		bar = "▰▰▰"
	case score >= 0.6:
		bar = "▰▰▱"
	case score >= 0.35:
		bar = "▰▱▱"
	default:
		bar = "▱▱▱"
	}
	return lipgloss.NewStyle().Foreground(color).Render(bar)
}

