// Auto-generated TypeScript type declarations for Clara MCP Tools.
// Generated by Clara Daemon / CLI.

/**
 * CloudEvent representation received by Clara script triggers.
 */
export interface CloudEvent<T = any> {
  specversion: string;
  id: string;
  source: string;
  type: string;
  time?: string;
  datacontenttype?: string;
  dataschema?: string;
  subject?: string;
  data: T;
}

/**
 * Map of tool names to their argument schemas and return types.
 */
export interface ClaraTools {
  /**
   * Execute a SQL statement and return the number of affected rows.
   */
  "db.exec": {
    args: {
      /** Optional positional parameters bound to the SQL statement. */
      params?: any[];
      /** SQL statement text to execute. */
      sql: string;
    };
    result: any;
  };
  /**
   * Execute a SQL query and return the results.
   */
  "db.query": {
    args: {
      /** Optional positional parameters bound to the SQL query. */
      params?: any[];
      /** SQL query text to execute. */
      sql: string;
    };
    result: any;
  };
  /**
   * Stage structured rows into a SQLite table with a single json column for later SQL processing.
   */
  "db.stage_rows": {
    args: {
      /** When true, clear the table before inserting rows. Defaults to true. */
      replace?: boolean;
      /** Array of JSON-serializable rows to store in the json column. */
      rows: any[];
      /** Destination table name. */
      table: string;
    };
    result: any;
  };
  /**
   * Perform a vector similarity search over a sqlite-vec table.
   */
  "db.vec_search": {
    args: {
      /** Maximum number of matches to return. Defaults to 10. */
      limit?: number;
      /** Optional maximum distance threshold for returned matches. */
      min_score?: number;
      /** Name of the vec0 virtual table to query. */
      table: string;
      /** Query vector represented as a JSON array of floats or raw bytes. */
      vector: any[];
    };
    result: any;
  };
  /**
   * Create a directory and all necessary parent directories.
   */
  "fs.create_directory": {
    args: {
      /** Path of the directory to create. */
      path: string;
    };
    result: any;
  };
  /**
   * Delete a file or empty directory.
   */
  "fs.delete_file": {
    args: {
      /** Path to the file or empty directory to delete. */
      path: string;
    };
    result: any;
  };
  /**
   * Get metadata about a file or directory (size, modification time, type).
   */
  "fs.get_file_info": {
    args: {
      /** Path to the file or directory. */
      path: string;
    };
    result: any;
  };
  /**
   * List the contents of a directory.
   */
  "fs.list_directory": {
    args: {
      /** Absolute or relative path to the directory to list. */
      path: string;
      /** Whether to recursively list subdirectories. Defaults to false. */
      recursive?: boolean;
    };
    result: any;
  };
  /**
   * Move or rename a file or directory.
   */
  "fs.move_file": {
    args: {
      /** Destination path. */
      destination: string;
      /** Source path. */
      source: string;
    };
    result: any;
  };
  /**
   * Return whether a file or directory exists at the given path.
   */
  "fs.path_exists": {
    args: {
      /** Path to check. */
      path: string;
    };
    result: any;
  };
  /**
   * Read the complete contents of a file from the filesystem.
   */
  "fs.read_file": {
    args: {
      /** Optional decoder: json, yaml. When set, returns parsed data instead of raw text. */
      decode?: string;
      /** Absolute or relative path to the file to read. */
      path: string;
    };
    result: any;
  };
  /**
   * Search for files using macOS mdfind (Spotlight).
   */
  "fs.search": {
    args: {
      /** Maximum number of results to return. */
      limit?: number;
      /** Optional directory to limit the search scope to. */
      path?: string;
      /** The mdfind query string (e.g. 'kMDItemDisplayName == "*.go"'). */
      query: string;
    };
    result: any;
  };
  /**
   * Search for files matching a glob pattern under a directory.
   */
  "fs.search_files": {
    args: {
      /** Glob pattern to match file names against (e.g. '*.go'). */
      pattern: string;
      /** Root directory to search in. */
      root: string;
    };
    result: any;
  };
  /**
   * Start watching a file or directory for changes. Returns a subscription_id that must be passed to watch_unsubscribe to stop watching. Emits fs/on_change notifications when changes are detected.
   */
  "fs.watch_subscribe": {
    args: {
      /** File or directory to watch. Supports ~ and environment variables. */
      path: string;
      /** Whether to recursively watch subdirectories. Defaults to false. */
      recursive?: boolean;
    };
    result: any;
  };
  /**
   * Stop a previously registered file watch.
   */
  "fs.watch_unsubscribe": {
    args: {
      /** The subscription_id returned by watch_subscribe. */
      subscription_id: string;
    };
    result: any;
  };
  /**
   * Write content to a file, creating it or overwriting it if it already exists.
   */
  "fs.write_file": {
    args: {
      /** Content to write to the file. */
      content?: string;
      /** Structured data to write. When set, encode must also be set. */
      data?: any;
      /** Optional encoder: json, yaml. */
      encode?: string;
      /** Absolute or relative path to the file to write. */
      path: string;
    };
    result: any;
  };
  /**
   * Deliver a question and return the user's answer. Returns a JSON object with 'selection' and optional 'custom_text'.
   */
  "notify.ask": {
    args: {
      /** Whether to provide a UI affordance for custom text feedback. Defaults to false. */
      allow_text?: boolean;
      /** The specific choices available to the user. Defaults to ["Approve", "Reject"] if omitted. */
      options?: Array<string>;
      /** The question to ask. */
      question: string;
    };
    result: any;
  };
  /**
   * Send a fire-and-forget notification message.
   */
  "notify.send": {
    args: {
      /** The message to deliver. */
      message: string;
    };
    result: any;
  };
  /**
   * Run a shell command
   */
  "shell.run": {
    args: {
      /** The shell command to run */
      command: string;
    };
    result: any;
  };
}

/**
 * Helper helper type for tool names.
 */
export type ClaraToolName = keyof ClaraTools;

/**
 * Call a Clara MCP tool by name with type safety.
 */
export declare function callTool<K extends ClaraToolName>(
  name: K,
  args: ClaraTools[K]["args"]
): Promise<ClaraTools[K]["result"]>;

/**
 * Read incoming CloudEvent payload passed from Clara supervisor.
 */
export declare function readEvent<T = any>(): Promise<CloudEvent<T>>;
