// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the gRPC Swift generator plugin for the protocol buffer compiler.
// Source: bridge.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/grpc/grpc-swift

import GRPCCore
import GRPCProtobuf

// MARK: - clara.bridge.v1.BridgeService

/// Namespace containing generated types for the "clara.bridge.v1.BridgeService" service.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
public enum Clara_Bridge_V1_BridgeService: Sendable {
    /// Service descriptor for the "clara.bridge.v1.BridgeService" service.
    public static let descriptor = GRPCCore.ServiceDescriptor(fullyQualifiedService: "clara.bridge.v1.BridgeService")
    /// Namespace for method metadata.
    public enum Method: Sendable {
        /// Namespace for "CallTool" metadata.
        public enum CallTool: Sendable {
            /// Request type for "CallTool".
            public typealias Input = Clara_Bridge_V1_CallToolRequest
            /// Response type for "CallTool".
            public typealias Output = Clara_Bridge_V1_CallToolResponse
            /// Descriptor for "CallTool".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "clara.bridge.v1.BridgeService"),
                method: "CallTool"
            )
        }
        /// Namespace for "Ping" metadata.
        public enum Ping: Sendable {
            /// Request type for "Ping".
            public typealias Input = Clara_Bridge_V1_PingRequest
            /// Response type for "Ping".
            public typealias Output = Clara_Bridge_V1_PingResponse
            /// Descriptor for "Ping".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "clara.bridge.v1.BridgeService"),
                method: "Ping"
            )
        }
        /// Descriptors for all methods in the "clara.bridge.v1.BridgeService" service.
        public static let descriptors: [GRPCCore.MethodDescriptor] = [
            CallTool.descriptor,
            Ping.descriptor
        ]
    }
}

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension GRPCCore.ServiceDescriptor {
    /// Service descriptor for the "clara.bridge.v1.BridgeService" service.
    public static let clara_bridge_v1_BridgeService = GRPCCore.ServiceDescriptor(fullyQualifiedService: "clara.bridge.v1.BridgeService")
}

// MARK: clara.bridge.v1.BridgeService (server)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Clara_Bridge_V1_BridgeService {
    /// Streaming variant of the service protocol for the "clara.bridge.v1.BridgeService" service.
    ///
    /// This protocol is the lowest-level of the service protocols generated for this service
    /// giving you the most flexibility over the implementation of your service. This comes at
    /// the cost of more verbose and less strict APIs. Each RPC requires you to implement it in
    /// terms of a request stream and response stream. Where only a single request or response
    /// message is expected, you are responsible for enforcing this invariant is maintained.
    ///
    /// Where possible, prefer using the stricter, less-verbose ``ServiceProtocol``
    /// or ``SimpleServiceProtocol`` instead.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > BridgeService provides access to native macOS capabilities (EventKit,
    /// > CoreSpotlight, FileSystem events) from the Go Clara daemon.
    public protocol StreamingServiceProtocol: GRPCCore.RegistrableRPCService {
        /// Handle the "CallTool" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > CallTool invokes a named native tool and returns a JSON-encoded result.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Clara_Bridge_V1_CallToolRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Clara_Bridge_V1_CallToolResponse` messages.
        func callTool(
            request: GRPCCore.StreamingServerRequest<Clara_Bridge_V1_CallToolRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Clara_Bridge_V1_CallToolResponse>

        /// Handle the "Ping" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Ping checks whether the Swift bridge process is alive and responsive.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Clara_Bridge_V1_PingRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Clara_Bridge_V1_PingResponse` messages.
        func ping(
            request: GRPCCore.StreamingServerRequest<Clara_Bridge_V1_PingRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Clara_Bridge_V1_PingResponse>
    }

    /// Service protocol for the "clara.bridge.v1.BridgeService" service.
    ///
    /// This protocol is higher level than ``StreamingServiceProtocol`` but lower level than
    /// the ``SimpleServiceProtocol``, it provides access to request and response metadata and
    /// trailing response metadata. If you don't need these then consider using
    /// the ``SimpleServiceProtocol``. If you need fine grained control over your RPCs then
    /// use ``StreamingServiceProtocol``.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > BridgeService provides access to native macOS capabilities (EventKit,
    /// > CoreSpotlight, FileSystem events) from the Go Clara daemon.
    public protocol ServiceProtocol: Clara_Bridge_V1_BridgeService.StreamingServiceProtocol {
        /// Handle the "CallTool" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > CallTool invokes a named native tool and returns a JSON-encoded result.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Clara_Bridge_V1_CallToolRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `Clara_Bridge_V1_CallToolResponse` message.
        func callTool(
            request: GRPCCore.ServerRequest<Clara_Bridge_V1_CallToolRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<Clara_Bridge_V1_CallToolResponse>

        /// Handle the "Ping" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Ping checks whether the Swift bridge process is alive and responsive.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Clara_Bridge_V1_PingRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `Clara_Bridge_V1_PingResponse` message.
        func ping(
            request: GRPCCore.ServerRequest<Clara_Bridge_V1_PingRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<Clara_Bridge_V1_PingResponse>
    }

    /// Simple service protocol for the "clara.bridge.v1.BridgeService" service.
    ///
    /// This is the highest level protocol for the service. The API is the easiest to use but
    /// doesn't provide access to request or response metadata. If you need access to these
    /// then use ``ServiceProtocol`` instead.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > BridgeService provides access to native macOS capabilities (EventKit,
    /// > CoreSpotlight, FileSystem events) from the Go Clara daemon.
    public protocol SimpleServiceProtocol: Clara_Bridge_V1_BridgeService.ServiceProtocol {
        /// Handle the "CallTool" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > CallTool invokes a named native tool and returns a JSON-encoded result.
        ///
        /// - Parameters:
        ///   - request: A `Clara_Bridge_V1_CallToolRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `Clara_Bridge_V1_CallToolResponse` to respond with.
        func callTool(
            request: Clara_Bridge_V1_CallToolRequest,
            context: GRPCCore.ServerContext
        ) async throws -> Clara_Bridge_V1_CallToolResponse

        /// Handle the "Ping" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Ping checks whether the Swift bridge process is alive and responsive.
        ///
        /// - Parameters:
        ///   - request: A `Clara_Bridge_V1_PingRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `Clara_Bridge_V1_PingResponse` to respond with.
        func ping(
            request: Clara_Bridge_V1_PingRequest,
            context: GRPCCore.ServerContext
        ) async throws -> Clara_Bridge_V1_PingResponse
    }
}

// Default implementation of 'registerMethods(with:)'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Clara_Bridge_V1_BridgeService.StreamingServiceProtocol {
    public func registerMethods<Transport>(with router: inout GRPCCore.RPCRouter<Transport>) where Transport: GRPCCore.ServerTransport {
        router.registerHandler(
            forMethod: Clara_Bridge_V1_BridgeService.Method.CallTool.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Clara_Bridge_V1_CallToolRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Clara_Bridge_V1_CallToolResponse>(),
            handler: { request, context in
                try await self.callTool(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: Clara_Bridge_V1_BridgeService.Method.Ping.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Clara_Bridge_V1_PingRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Clara_Bridge_V1_PingResponse>(),
            handler: { request, context in
                try await self.ping(
                    request: request,
                    context: context
                )
            }
        )
    }
}

// Default implementation of streaming methods from 'StreamingServiceProtocol'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Clara_Bridge_V1_BridgeService.ServiceProtocol {
    public func callTool(
        request: GRPCCore.StreamingServerRequest<Clara_Bridge_V1_CallToolRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Clara_Bridge_V1_CallToolResponse> {
        let response = try await self.callTool(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }

    public func ping(
        request: GRPCCore.StreamingServerRequest<Clara_Bridge_V1_PingRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Clara_Bridge_V1_PingResponse> {
        let response = try await self.ping(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }
}

// Default implementation of methods from 'ServiceProtocol'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Clara_Bridge_V1_BridgeService.SimpleServiceProtocol {
    public func callTool(
        request: GRPCCore.ServerRequest<Clara_Bridge_V1_CallToolRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<Clara_Bridge_V1_CallToolResponse> {
        return GRPCCore.ServerResponse<Clara_Bridge_V1_CallToolResponse>(
            message: try await self.callTool(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }

    public func ping(
        request: GRPCCore.ServerRequest<Clara_Bridge_V1_PingRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<Clara_Bridge_V1_PingResponse> {
        return GRPCCore.ServerResponse<Clara_Bridge_V1_PingResponse>(
            message: try await self.ping(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }
}

// MARK: clara.bridge.v1.BridgeService (client)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Clara_Bridge_V1_BridgeService {
    /// Generated client protocol for the "clara.bridge.v1.BridgeService" service.
    ///
    /// You don't need to implement this protocol directly, use the generated
    /// implementation, ``Client``.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > BridgeService provides access to native macOS capabilities (EventKit,
    /// > CoreSpotlight, FileSystem events) from the Go Clara daemon.
    public protocol ClientProtocol: Sendable {
        /// Call the "CallTool" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > CallTool invokes a named native tool and returns a JSON-encoded result.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Clara_Bridge_V1_CallToolRequest` message.
        ///   - serializer: A serializer for `Clara_Bridge_V1_CallToolRequest` messages.
        ///   - deserializer: A deserializer for `Clara_Bridge_V1_CallToolResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func callTool<Result>(
            request: GRPCCore.ClientRequest<Clara_Bridge_V1_CallToolRequest>,
            serializer: some GRPCCore.MessageSerializer<Clara_Bridge_V1_CallToolRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Clara_Bridge_V1_CallToolResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Clara_Bridge_V1_CallToolResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "Ping" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Ping checks whether the Swift bridge process is alive and responsive.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Clara_Bridge_V1_PingRequest` message.
        ///   - serializer: A serializer for `Clara_Bridge_V1_PingRequest` messages.
        ///   - deserializer: A deserializer for `Clara_Bridge_V1_PingResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func ping<Result>(
            request: GRPCCore.ClientRequest<Clara_Bridge_V1_PingRequest>,
            serializer: some GRPCCore.MessageSerializer<Clara_Bridge_V1_PingRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Clara_Bridge_V1_PingResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Clara_Bridge_V1_PingResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable
    }

    /// Generated client for the "clara.bridge.v1.BridgeService" service.
    ///
    /// The ``Client`` provides an implementation of ``ClientProtocol`` which wraps
    /// a `GRPCCore.GRPCCClient`. The underlying `GRPCClient` provides the long-lived
    /// means of communication with the remote peer.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > BridgeService provides access to native macOS capabilities (EventKit,
    /// > CoreSpotlight, FileSystem events) from the Go Clara daemon.
    public struct Client<Transport>: ClientProtocol where Transport: GRPCCore.ClientTransport {
        private let client: GRPCCore.GRPCClient<Transport>

        /// Creates a new client wrapping the provided `GRPCCore.GRPCClient`.
        ///
        /// - Parameters:
        ///   - client: A `GRPCCore.GRPCClient` providing a communication channel to the service.
        public init(wrapping client: GRPCCore.GRPCClient<Transport>) {
            self.client = client
        }

        /// Call the "CallTool" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > CallTool invokes a named native tool and returns a JSON-encoded result.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Clara_Bridge_V1_CallToolRequest` message.
        ///   - serializer: A serializer for `Clara_Bridge_V1_CallToolRequest` messages.
        ///   - deserializer: A deserializer for `Clara_Bridge_V1_CallToolResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func callTool<Result>(
            request: GRPCCore.ClientRequest<Clara_Bridge_V1_CallToolRequest>,
            serializer: some GRPCCore.MessageSerializer<Clara_Bridge_V1_CallToolRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Clara_Bridge_V1_CallToolResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Clara_Bridge_V1_CallToolResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Clara_Bridge_V1_BridgeService.Method.CallTool.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "Ping" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Ping checks whether the Swift bridge process is alive and responsive.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Clara_Bridge_V1_PingRequest` message.
        ///   - serializer: A serializer for `Clara_Bridge_V1_PingRequest` messages.
        ///   - deserializer: A deserializer for `Clara_Bridge_V1_PingResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func ping<Result>(
            request: GRPCCore.ClientRequest<Clara_Bridge_V1_PingRequest>,
            serializer: some GRPCCore.MessageSerializer<Clara_Bridge_V1_PingRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Clara_Bridge_V1_PingResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Clara_Bridge_V1_PingResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Clara_Bridge_V1_BridgeService.Method.Ping.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }
    }
}

// Helpers providing default arguments to 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Clara_Bridge_V1_BridgeService.ClientProtocol {
    /// Call the "CallTool" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > CallTool invokes a named native tool and returns a JSON-encoded result.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Clara_Bridge_V1_CallToolRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func callTool<Result>(
        request: GRPCCore.ClientRequest<Clara_Bridge_V1_CallToolRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Clara_Bridge_V1_CallToolResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.callTool(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Clara_Bridge_V1_CallToolRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Clara_Bridge_V1_CallToolResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "Ping" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Ping checks whether the Swift bridge process is alive and responsive.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Clara_Bridge_V1_PingRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func ping<Result>(
        request: GRPCCore.ClientRequest<Clara_Bridge_V1_PingRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Clara_Bridge_V1_PingResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.ping(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Clara_Bridge_V1_PingRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Clara_Bridge_V1_PingResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }
}

// Helpers providing sugared APIs for 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Clara_Bridge_V1_BridgeService.ClientProtocol {
    /// Call the "CallTool" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > CallTool invokes a named native tool and returns a JSON-encoded result.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func callTool<Result>(
        _ message: Clara_Bridge_V1_CallToolRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Clara_Bridge_V1_CallToolResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Clara_Bridge_V1_CallToolRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.callTool(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "Ping" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Ping checks whether the Swift bridge process is alive and responsive.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func ping<Result>(
        _ message: Clara_Bridge_V1_PingRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Clara_Bridge_V1_PingResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Clara_Bridge_V1_PingRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.ping(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }
}