package typestub

import (
	"encoding/json"
	"fmt"
	"sort"
	"strings"

	"github.com/brightpuddle/clara/internal/registry"
	"github.com/mark3labs/mcp-go/mcp"
)

// GenerateTypeScript generates TypeScript ambient declarations (.d.ts)
// for all tools currently registered in the Clara registry.
func GenerateTypeScript(reg *registry.Registry) string {
	tools := reg.Tools()
	return GenerateTypeScriptFromTools(tools)
}

// GenerateTypeScriptFromTools generates TypeScript definitions from a slice of ToolInfo.
func GenerateTypeScriptFromTools(tools []registry.ToolInfo) string {
	var b strings.Builder

	b.WriteString("// Auto-generated TypeScript type declarations for Clara MCP Tools.\n")
	b.WriteString("// Generated by Clara Daemon / CLI.\n\n")

	b.WriteString("/**\n")
	b.WriteString(" * CloudEvent representation received by Clara script triggers.\n")
	b.WriteString(" */\n")
	b.WriteString("export interface CloudEvent<T = any> {\n")
	b.WriteString("  specversion: string;\n")
	b.WriteString("  id: string;\n")
	b.WriteString("  source: string;\n")
	b.WriteString("  type: string;\n")
	b.WriteString("  time?: string;\n")
	b.WriteString("  datacontenttype?: string;\n")
	b.WriteString("  dataschema?: string;\n")
	b.WriteString("  subject?: string;\n")
	b.WriteString("  data: T;\n")
	b.WriteString("}\n\n")

	b.WriteString("/**\n")
	b.WriteString(" * Map of tool names to their argument schemas and return types.\n")
	b.WriteString(" */\n")
	b.WriteString("export interface ClaraTools {\n")

	// Sort tools deterministically by name
	sorted := make([]registry.ToolInfo, len(tools))
	copy(sorted, tools)
	sort.Slice(sorted, func(i, j int) bool {
		return sorted[i].Name < sorted[j].Name
	})

	for _, tool := range sorted {
		if strings.HasSuffix(tool.Name, ".clara_list_events") {
			continue
		}

		if tool.Description != "" {
			b.WriteString(fmt.Sprintf("  /**\n   * %s\n   */\n", formatJSDoc(tool.Description)))
		}

		b.WriteString(fmt.Sprintf("  %q: {\n", tool.Name))
		b.WriteString(fmt.Sprintf("    args: %s;\n", generateInputType(tool.Spec.InputSchema, "    ")))
		b.WriteString("    result: any;\n")
		b.WriteString("  };\n")
	}

	b.WriteString("}\n\n")

	b.WriteString("/**\n")
	b.WriteString(" * Helper helper type for tool names.\n")
	b.WriteString(" */\n")
	b.WriteString("export type ClaraToolName = keyof ClaraTools;\n\n")

	b.WriteString("/**\n")
	b.WriteString(" * Call a Clara MCP tool by name with type safety.\n")
	b.WriteString(" */\n")
	b.WriteString("export declare function callTool<K extends ClaraToolName>(\n")
	b.WriteString("  name: K,\n")
	b.WriteString("  args: ClaraTools[K][\"args\"]\n")
	b.WriteString("): Promise<ClaraTools[K][\"result\"]>;\n\n")

	b.WriteString("/**\n")
	b.WriteString(" * Read incoming CloudEvent payload passed from Clara supervisor.\n")
	b.WriteString(" */\n")
	b.WriteString("export declare function readEvent<T = any>(): Promise<CloudEvent<T>>;\n")

	return b.String()
}

func generateInputType(schema mcp.ToolInputSchema, indent string) string {
	if len(schema.Properties) == 0 {
		return "Record<string, never> | Record<string, any>"
	}

	requiredSet := make(map[string]bool, len(schema.Required))
	for _, req := range schema.Required {
		requiredSet[req] = true
	}

	// Sort property keys deterministically
	keys := make([]string, 0, len(schema.Properties))
	for k := range schema.Properties {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var b strings.Builder
	b.WriteString("{\n")

	for _, k := range keys {
		prop := schema.Properties[k]
		propMap, isMap := prop.(map[string]any)

		desc := ""
		tsType := "any"

		if isMap {
			if d, ok := propMap["description"].(string); ok && d != "" {
				desc = d
			}
			tsType = jsonSchemaPropToTSType(propMap)
		}

		if desc != "" {
			b.WriteString(fmt.Sprintf("%s  /** %s */\n", indent, escapeComment(desc)))
		}

		opt := "?"
		if requiredSet[k] {
			opt = ""
		}

		b.WriteString(fmt.Sprintf("%s  %s%s: %s;\n", indent, quotePropIfNeeded(k), opt, tsType))
	}

	b.WriteString(indent + "}")
	return b.String()
}

func jsonSchemaPropToTSType(prop map[string]any) string {
	typ, _ := prop["type"].(string)

	if typ == "" {
		if _, ok := prop["enum"]; ok {
			typ = "enum"
		}
	}

	switch typ {
	case "string":
		if enumVals, ok := prop["enum"].([]any); ok && len(enumVals) > 0 {
			enums := make([]string, 0, len(enumVals))
			for _, ev := range enumVals {
				enums = append(enums, fmt.Sprintf("%q", fmt.Sprint(ev)))
			}
			return strings.Join(enums, " | ")
		}
		return "string"
	case "number":
		return "number"
	case "integer":
		return "number"
	case "boolean":
		return "boolean"
	case "array":
		if items, ok := prop["items"].(map[string]any); ok {
			return fmt.Sprintf("Array<%s>", jsonSchemaPropToTSType(items))
		}
		return "any[]"
	case "object":
		if props, ok := prop["properties"].(map[string]any); ok && len(props) > 0 {
			nestedSchema := mcp.ToolInputSchema{
				Properties: props,
			}
			if req, ok := prop["required"].([]string); ok {
				nestedSchema.Required = req
			} else if reqAny, ok := prop["required"].([]any); ok {
				for _, r := range reqAny {
					if s, ok := r.(string); ok {
						nestedSchema.Required = append(nestedSchema.Required, s)
					}
				}
			}
			return generateInputType(nestedSchema, "    ")
		}
		return "Record<string, any>"
	default:
		return "any"
	}
}

func quotePropIfNeeded(prop string) string {
	isValidIdent := true
	for i, r := range prop {
		if i == 0 && !((r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || r == '_' || r == '$') {
			isValidIdent = false
			break
		}
		if !((r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') || r == '_' || r == '$') {
			isValidIdent = false
			break
		}
	}
	if isValidIdent {
		return prop
	}
	b, _ := json.Marshal(prop)
	return string(b)
}

func formatJSDoc(doc string) string {
	doc = escapeComment(doc)
	lines := strings.Split(doc, "\n")
	return strings.Join(lines, "\n   * ")
}

func escapeComment(s string) string {
	s = strings.ReplaceAll(s, "*/", "* /")
	return s
}
